version: 1
formatters:
  default:
    format: '%(asctime)s %(levelname)s %(name)s %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
    stream: ext://sys.stdout
  file:
    class : logging.handlers.RotatingFileHandler
    formatter: default
    filename: bot.log
    maxBytes: 0
    backupCount: 0
loggers:
  cloaked_chatter:
    level: DEBUG
    handlers: [console, file]
    propagate: no
